
services:
  backend:
    build:
      context: ./ppdoarbackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Changed to match your server.port=8080
    networks:
      - app-network
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/ppdo_ar_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: a4IaFKF5NKCmCk5Ehe9uwoPrHDnnwT8GCYyX+xqtLgI=
      UPLOAD_DIR: /app/project-images/
    volumes:
      - uploads:/app/project-images
    restart: unless-stopped

  frontend:
    build:
      context: ./ppdo-ar
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  mariadb:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ppdo_ar_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
  uploads:

networks:
  app-network:
    driver: bridge